language: node_js
node_js:
  - "lts/*"
  - "8.1.3"
before_install:
  - sudo apt-get install ncftp
after_success:
  - yarn run build
  - ncftpput -R -v -u $TRAVIS_USER -p $TRAVIS_PASS ftp.gerardo-junior.com /jokenpo dist/*