version: '3'
services:
  node:
    image: node:8.1.3
    volumes:
        - .:/src
    working_dir: "/src"
    command: ["yarn", "install", "--non-interactive"]
    entrypoint: "yarn run build"
    tty: true