version: '3'
services:
  node:
    image: gerardojunior/nodejs:stable
    volumes:
        - .:/src
    ports:
        - 8000:8000
    working_dir: "/src"
    command: ["npm", "install", "--non-interactive"]
    entrypoint: "npm run start -- -p 8000"
    tty: true