version: '3'
services:
  node:
    image: node:8.1.3
    volumes:
        - .:/src
    ports:
        - 8000:8000
    working_dir: "/src"
    command: ["yarn", "install", "--non-interactive"]
    entrypoint: "yarn run start -- -p 8000"
    tty: true